services:
  webback:
    build: ./Backend
    container_name: webback
    expose:
      - "8080"
    networks:
      - app-net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./WebConfig/nginxweb.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webback
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
